{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "apollo.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "apollo.labels" . | nindent 4 }}
    app.kubernetes.io/component: manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "apollo.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "apollo.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
{{- end }}