//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CollectedData) DeepCopyInto(out *CollectedData) {
	*out = *in
	in.CollectionTime.DeepCopyInto(&out.CollectionTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CollectedData.
func (in *CollectedData) DeepCopy() *CollectedData {
	if in == nil {
		return nil
	}
	out := new(CollectedData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisAnalysis) DeepCopyInto(out *DiagnosisAnalysis) {
	*out = *in
	if in.Recommendations != nil {
		in, out := &in.Recommendations, &out.Recommendations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisAnalysis.
func (in *DiagnosisAnalysis) DeepCopy() *DiagnosisAnalysis {
	if in == nil {
		return nil
	}
	out := new(DiagnosisAnalysis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisError) DeepCopyInto(out *DiagnosisError) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisError.
func (in *DiagnosisError) DeepCopy() *DiagnosisError {
	if in == nil {
		return nil
	}
	out := new(DiagnosisError)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisPolicy) DeepCopyInto(out *DiagnosisPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisPolicy.
func (in *DiagnosisPolicy) DeepCopy() *DiagnosisPolicy {
	if in == nil {
		return nil
	}
	out := new(DiagnosisPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiagnosisPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisPolicyList) DeepCopyInto(out *DiagnosisPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DiagnosisPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisPolicyList.
func (in *DiagnosisPolicyList) DeepCopy() *DiagnosisPolicyList {
	if in == nil {
		return nil
	}
	out := new(DiagnosisPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiagnosisPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisPolicySpec) DeepCopyInto(out *DiagnosisPolicySpec) {
	*out = *in
	if in.TargetNamespaces != nil {
		in, out := &in.TargetNamespaces, &out.TargetNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PodSelector != nil {
		in, out := &in.PodSelector, &out.PodSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.TriggerConditions != nil {
		in, out := &in.TriggerConditions, &out.TriggerConditions
		*out = make([]PodConditionTrigger, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LLMConfig.DeepCopyInto(&out.LLMConfig)
	if in.DiagnosisSettings != nil {
		in, out := &in.DiagnosisSettings, &out.DiagnosisSettings
		*out = new(DiagnosisSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisPolicySpec.
func (in *DiagnosisPolicySpec) DeepCopy() *DiagnosisPolicySpec {
	if in == nil {
		return nil
	}
	out := new(DiagnosisPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisPolicyStatus) DeepCopyInto(out *DiagnosisPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastDiagnosisTime != nil {
		in, out := &in.LastDiagnosisTime, &out.LastDiagnosisTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisPolicyStatus.
func (in *DiagnosisPolicyStatus) DeepCopy() *DiagnosisPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(DiagnosisPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisReport) DeepCopyInto(out *DiagnosisReport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisReport.
func (in *DiagnosisReport) DeepCopy() *DiagnosisReport {
	if in == nil {
		return nil
	}
	out := new(DiagnosisReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiagnosisReport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisReportList) DeepCopyInto(out *DiagnosisReportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DiagnosisReport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisReportList.
func (in *DiagnosisReportList) DeepCopy() *DiagnosisReportList {
	if in == nil {
		return nil
	}
	out := new(DiagnosisReportList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiagnosisReportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisReportReference) DeepCopyInto(out *DiagnosisReportReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisReportReference.
func (in *DiagnosisReportReference) DeepCopy() *DiagnosisReportReference {
	if in == nil {
		return nil
	}
	out := new(DiagnosisReportReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisReportSpec) DeepCopyInto(out *DiagnosisReportSpec) {
	*out = *in
	out.TargetPod = in.TargetPod
	out.PolicyRef = in.PolicyRef
	in.TriggerCondition.DeepCopyInto(&out.TriggerCondition)
	in.CollectedData.DeepCopyInto(&out.CollectedData)
	in.Analysis.DeepCopyInto(&out.Analysis)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisReportSpec.
func (in *DiagnosisReportSpec) DeepCopy() *DiagnosisReportSpec {
	if in == nil {
		return nil
	}
	out := new(DiagnosisReportSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisReportStatus) DeepCopyInto(out *DiagnosisReportStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Error != nil {
		in, out := &in.Error, &out.Error
		*out = new(DiagnosisError)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisReportStatus.
func (in *DiagnosisReportStatus) DeepCopy() *DiagnosisReportStatus {
	if in == nil {
		return nil
	}
	out := new(DiagnosisReportStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisRequest) DeepCopyInto(out *DiagnosisRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisRequest.
func (in *DiagnosisRequest) DeepCopy() *DiagnosisRequest {
	if in == nil {
		return nil
	}
	out := new(DiagnosisRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiagnosisRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisRequestList) DeepCopyInto(out *DiagnosisRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DiagnosisRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisRequestList.
func (in *DiagnosisRequestList) DeepCopy() *DiagnosisRequestList {
	if in == nil {
		return nil
	}
	out := new(DiagnosisRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiagnosisRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisRequestSpec) DeepCopyInto(out *DiagnosisRequestSpec) {
	*out = *in
	out.TargetPod = in.TargetPod
	out.PolicyRef = in.PolicyRef
	if in.TriggerCondition != nil {
		in, out := &in.TriggerCondition, &out.TriggerCondition
		*out = new(TriggerCondition)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisRequestSpec.
func (in *DiagnosisRequestSpec) DeepCopy() *DiagnosisRequestSpec {
	if in == nil {
		return nil
	}
	out := new(DiagnosisRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisRequestStatus) DeepCopyInto(out *DiagnosisRequestStatus) {
	*out = *in
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DiagnosisReportRef != nil {
		in, out := &in.DiagnosisReportRef, &out.DiagnosisReportRef
		*out = new(DiagnosisReportReference)
		**out = **in
	}
	if in.RequestTime != nil {
		in, out := &in.RequestTime, &out.RequestTime
		*out = (*in).DeepCopy()
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.CompletionTime != nil {
		in, out := &in.CompletionTime, &out.CompletionTime
		*out = (*in).DeepCopy()
	}
	if in.Error != nil {
		in, out := &in.Error, &out.Error
		*out = new(DiagnosisError)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisRequestStatus.
func (in *DiagnosisRequestStatus) DeepCopy() *DiagnosisRequestStatus {
	if in == nil {
		return nil
	}
	out := new(DiagnosisRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiagnosisSettings) DeepCopyInto(out *DiagnosisSettings) {
	*out = *in
	if in.MaxLogLines != nil {
		in, out := &in.MaxLogLines, &out.MaxLogLines
		*out = new(int)
		**out = **in
	}
	if in.RetryInterval != nil {
		in, out := &in.RetryInterval, &out.RetryInterval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiagnosisSettings.
func (in *DiagnosisSettings) DeepCopy() *DiagnosisSettings {
	if in == nil {
		return nil
	}
	out := new(DiagnosisSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMConfiguration) DeepCopyInto(out *LLMConfiguration) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMConfiguration.
func (in *LLMConfiguration) DeepCopy() *LLMConfiguration {
	if in == nil {
		return nil
	}
	out := new(LLMConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodConditionCheck) DeepCopyInto(out *PodConditionCheck) {
	*out = *in
	if in.MinDuration != nil {
		in, out := &in.MinDuration, &out.MinDuration
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodConditionCheck.
func (in *PodConditionCheck) DeepCopy() *PodConditionCheck {
	if in == nil {
		return nil
	}
	out := new(PodConditionCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodConditionTrigger) DeepCopyInto(out *PodConditionTrigger) {
	*out = *in
	if in.MinDuration != nil {
		in, out := &in.MinDuration, &out.MinDuration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]PodConditionCheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodConditionTrigger.
func (in *PodConditionTrigger) DeepCopy() *PodConditionTrigger {
	if in == nil {
		return nil
	}
	out := new(PodConditionTrigger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodReference) DeepCopyInto(out *PodReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodReference.
func (in *PodReference) DeepCopy() *PodReference {
	if in == nil {
		return nil
	}
	out := new(PodReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyReference) DeepCopyInto(out *PolicyReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyReference.
func (in *PolicyReference) DeepCopy() *PolicyReference {
	if in == nil {
		return nil
	}
	out := new(PolicyReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetPodReference) DeepCopyInto(out *TargetPodReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetPodReference.
func (in *TargetPodReference) DeepCopy() *TargetPodReference {
	if in == nil {
		return nil
	}
	out := new(TargetPodReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriggerCondition) DeepCopyInto(out *TriggerCondition) {
	*out = *in
	in.DetectedAt.DeepCopyInto(&out.DetectedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriggerCondition.
func (in *TriggerCondition) DeepCopy() *TriggerCondition {
	if in == nil {
		return nil
	}
	out := new(TriggerCondition)
	in.DeepCopyInto(out)
	return out
}
