{{- if .Values.webui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "apollo.fullname" . }}-webui
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "apollo.labels" . | nindent 4 }}
    app.kubernetes.io/component: webui
spec:
  type: {{ .Values.webui.service.type }}
  ports:
  - port: {{ .Values.webui.service.port }}
    targetPort: {{ .Values.webui.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "apollo.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: webui
{{- end }}